Added a wide view logo property
TAMULib/SAGE pull request #317
Opened 2021-03-03 17:31 UTC by rladdusaw

Resolves #310

2021-03-03 19:25 UTC, jeremythuff requested changes

2021-03-03 19:25 UTC, jeremythuff commented on src/main/webapp/app/views/discovery/discovery-context.html
> +        <div ng-style="{'background-image':'url({{discoveryContext.logoUrl}})'}" class="panel panel-default information-box logo-information-box narrow-logo">
According to [this](https://docs.angularjs.org/api/ng/directive/ngStyle) there are known issues with using string interpolation within the ngStyle. This whole object should be expressed in the controller on the scope. We can use ES6 style interpolation at that point. BUT if we do that we will also need to add `"esversion": 6` to the .jshintrc (as I did [here](https://github.com/TAMULib/SAGE/pull/318/files#diff-c3ca886e85c3a97b5cc4c34d04e5b9d5c78359b1e69fd09b74a842b5dea81bb0L1))

2021-03-03 19:25 UTC, jeremythuff commented on src/main/webapp/app/views/discovery/discovery-context.html
> +              <a ng-if="discoveryContext.infoLinkUrl" href="{{discoveryContext.infoLinkUrl}}">{{discoveryContext.infoLinkText}}</a>
Same comment as above...

2021-03-03 19:25 UTC, jeremythuff commented on src/main/webapp/app/views/discovery/discovery-context.html
> +        <div ng-style="{'background-image':'url({{discoveryContext.wideLogoUrl}})'}" class="panel panel-default information-box logo-information-box wide-logo">
Same comment as above

2021-03-03 19:25 UTC, jeremythuff commented on src/main/webapp/app/views/discovery/discovery-context.html
> +      <div ng-style="{'background-image':'url({{discoveryContext.logoUrl}})'}" ng-if="discoveryContext.logoUrl && !discoveryContext.wideLogoUrl" class="panel panel-default information-box logo-inform
same comment as above...

2021-03-03 19:25 UTC, jeremythuff commented on src/main/webapp/app/views/discovery/discovery-context.html
> +        <div ng-style="{'background-image':'url({{discoveryContext.logoUrl}})'}" class="panel panel-default information-box logo-information-box narrow-logo">
In addition to the interpolation issue, it would also be preferable to keep all that json out of the view, imo.

2021-03-08 14:42 UTC, wwelling approved these changes

2021-03-08 16:04 UTC, merged