Google scripts added
TAMULib/SAGE pull request #547
Opened 2023-07-21 20:15 UTC by qtamu

# Description
Added an scripts to the Dockerfile to allow new Google tag manager tags to be injected into the index.html file at build time. On my pc I had to use LF end of line sequence instead of CRLF for Mac users in order to run my shell script. Two txt files were added for the place holders to store the generic Google tags, all that is needed is to add the tag id where specified.   The script is located outside of the Dockerfile in docker-entrypoint if one does not want to use it at build time.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Toolchain:
* SDK:

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-25 14:46 UTC, rmathew1011 requested changes

2023-07-25 14:46 UTC, rmathew1011 commented on .gitignore
> +/SAGE/build/Gtm.txt
Could you please add newline here

2023-07-28 14:34 UTC, rmathew1011 approved these changes

2023-07-28 14:34 UTC, rmathew1011 commented on src/main/resources/templates/index.html
> +</html>
Please add a new line here.

2023-07-31 20:27 UTC, jcreel approved these changes
Build works, and analytics meet new requirements.

2023-07-31 20:27 UTC, merged